### ISSUE TITLE
How to run this demo? 

### ISSUE THREAD

**Issue by SJanJan** [LinusBorg/composition-api-demos#18]
These demos are very nice,but I can't run this project,I have used yarn install or npm install,but it can't  to setup, I'm very sad😭,please help me,thank you.

**Comment by ycmjason** [comment]
1. `yarn` or `npm install`
2. `yarn serve` or `npm run serve`
3. Go to the link displayed on your terminal.

**Comment by SJanJan** [comment]
Thanks ,big brather!
