### ISSUE TITLE
When use `createComponent`?

### ISSUE THREAD

**Issue by thearabbit** [LinusBorg/composition-api-demos#22]
When use `createComponent`?

**Comment by LinusBorg** [comment]
When you use Typescript. The function itself doesn't do anything, it's just necessary for type inference.

**Comment by thearabbit** [comment]
thanks for your reply.
Haha but sometime, I seen it in `.js file`

**Comment by LinusBorg** [comment]
Yeah but then my editor can use Typescript to give some intellisense even in js
